ALTER TABLE "Player" ADD COLUMN "nameSize" REAL NOT NULL DEFAULT 1;
ALTER TABLE "Player" ADD COLUMN "nameOffsetX" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "nameOffsetY" REAL NOT NULL DEFAULT 0;
ALTER TABLE "Player" ADD COLUMN "nameBackground" TEXT NOT NULL DEFAULT 'solid';
ALTER TABLE "Player" ADD COLUMN "nameBackgroundColor" TEXT NOT NULL DEFAULT '#090305';
