ALTER TABLE "Player" ADD COLUMN "positionX" REAL;
ALTER TABLE "Player" ADD COLUMN "positionY" REAL;
ALTER TABLE "Player" ADD COLUMN "displaySize" REAL NOT NULL DEFAULT 1;
ALTER TABLE "Player" ADD COLUMN "displayLayer" INTEGER NOT NULL DEFAULT 0;
